### ISSUE TITLE
Application not visible

### ISSUE THREAD

**Issue by RahimRamzanAli** [MohammedNoureldin/frappe-oidc-extended#2]
I have installed it on my Docker, and the app is successfully installed but I can not the any option with the name Social Login (OIDC) provider, I can only the the default social login key which is implemented with my keycloak but I am not able to do group mappings with it. Can you please help me

**Comment by MohammedNoureldin** [comment]
Hi @RahimRamzanAli,

in the search box look for Extended OIDC. Here you will be able to create and attach the extended settings.

**Comment by RahimRamzanAli** [comment]
Thankyou for your quick reply, yes i have found the Extended OIDC in the search box, I have configured it but it is not working, when I try to login via keycloak I am able to login but the users type is website user, not that group which I have added Extended OIDC. 

Is there anything I need to configure on keycloak ?

**Comment by MohammedNoureldin** [comment]
@RahimRamzanAli could you show a screenshot with the problem? I don't understand the exact issue.

Do you particularly mean, that the type of the user should be changed from website to system for this to work properly?

**Comment by RahimRamzanAli** [comment]
This is my OIDC Extended setting where I have mapped the IT group as an Administrator and the Management group as a System Manager for ERPNext. The IT and Management groups are present in my keycloak.

<img width="801" alt="erpnext_SSO" src="https://github.com/MohammedNoureldin/frappe-oidc-extended/assets/138520445/62ebcb27-298b-4631-a054-88502c866526">

Now when I try to log in with my keycloak username Test User which is in the IT group, should be Mapped as an Administrator but it is mapped as a website user.

<img width="959" alt="Capture" src="https://github.com/MohammedNoureldin/frappe-oidc-extended/assets/138520445/35296469-bf2f-4612-9a4d-587f0e1e6830">

I hope you will understand my problem now, is there anything I need to change on my keycloak side please let me know and once again thankyou are your prompt response.

**Comment by MohammedNoureldin** [comment]
The first thing I see here that, if I am not wrong, you compare the *user type* with *user roles*, which are two different things.

Did you open the test user and checked its *roles and permissions*? Please check that in the administration panel and post a screenshot of that.

**Comment by RahimRamzanAli** [comment]
<img width="801" alt="erpnext_user_roles" src="https://github.com/MohammedNoureldin/frappe-oidc-extended/assets/138520445/4ccd6ca5-afe0-4ee2-b9be-552eeb7c3f46">

The roles are empty and whenever I try to log in via keycloak with any users I see their user type is the website user.

**Comment by MohammedNoureldin** [comment]
Are you sure that the groups are mapped and added to your Access token / Id token? It seems like the groups are not there at all. Please make sure the groups are added to the token. If you are not sure how to check that, please post access and id token here and I will check that (don't do that from a a production environment, of course).

**Comment by RahimRamzanAli** [comment]
> Are you sure that the groups are mapped and added to your Access token / Id token in Keycloak? It looks like the groups are not there at all.
> 
> Please make sure the groups are added to the token. If you are not sure how to check that, please post access and id token here and I will check that (don't do that from a a production environment, of course).
> 
> Regarding that user type, if the user does not exist, a new user will be created of type _System user_. If the user already exists, its type is not changed, so if your user is already of type Website user, it will stay like that. But as said, the type of the user has nothing to do with permission mapping.
> 
> https://github.com/MohammedNoureldin/frappe-oidc-extended/blob/41c746156ef2a0ad20814a91a730e9891dfbce63/oidc_extended/callback.py#L77-L97
> 
> So as said, please verify that the groups are added to the token in Keycloak.

Thankyou so much for your help and support, it is working now
